sudo: required
language: node_js
node_js:
    - '12'
branches:
  only:
    - main
before_install:
    - npm run audit:ci
install:
    - npm ci
matrix:
    fast_finish: true
    include:
        - name: 'Lint, Compile, Unit Test'
          script:
              - npm run lint
              - npm run compile
              - npm test